name: 'Deploy to Heroku'
on: workflow_dispatch # Will be triggered manually
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku
        id: heroku
        uses: jctaveras/heroku-deploy@v2.1.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }} # your heroku email
          api_key: ${{ secrets.HEROKU_API_KEY }} # your  heroku api key
          app_name: ${{ secrets.HEROKU_APP_NAME }} # you aplication name
          dockerfile_path: '/home/runner/work/Enisn.Abp.AspNetCore.Mvc.UI.Theme.Material/Enisn.Abp.AspNetCore.Mvc.UI.Theme.Material' # set the path to the folder wher the Dokerfile is located
          options: '' # Docker Build Options